Jakub Catlos added FMA dataset
pdokoupil/EasyStudy pull request #1
Opened 2023-05-15 20:02 UTC by jcatlos

Pridal som FMA music dataset ako zápočtový projekt

2023-06-12 14:55 UTC, pdokoupil requested changes
V  zásadě to vypadá dobře, zkoušel jsem funkcionalitu, s drobnými úpravami (viz komentáře), to vypadalo funkčně.

2023-06-12 14:55 UTC, pdokoupil commented on server/plugins/fastcompare/algo/wrappers/fma_loader.py
> +            )
Chybějící "," za ")"

2023-06-12 14:55 UTC, pdokoupil commented on server/plugins/utils/fma_fetch_album.py
> +    img_data_path = Path('server/static/datasets/fma/img')
Potenciálně problematické, fungovalo Vám to bez problémů? Čekal bych, že když spustíte tento skript z adresáře kde se nachází, tak to tu cestu nenajde. Relativně snadný fix (ikdyž možná ošklivý) by mohlo být nahrazení za
```
dataset_path = os.path.join(get_abs_project_root_path(), 'static', 'datasets')
img_data_path = Path(f'{dataset_path}/fma/img')
tracks_path = Path(f'{dataset_path}/fma/tracks.csv')
```
čímž získáte abs cestu k "server/" adresáři místo aktuálně použité relativní

2023-06-12 14:55 UTC, pdokoupil commented on server/plugins/utils/fma_fetch_album.py
> +import discogs_client as dc
V zásadě detail, ale ideálně prosím přidejte `RUN pip install python3-discogs-client` do Dockerfile souboru

2023-06-12 14:55 UTC, pdokoupil commented on .gitignore
> -cache
Ty změny v .gitignore se hodí lokálně, ale pokud možno je prosím odstraňte z pull requestu

2023-07-28 09:43 UTC, jcatlos commented
Zmeny implementované a zacommitované

2023-07-30 17:39 UTC, pdokoupil approved these changes

2023-07-30 17:39 UTC, merged